[project]
name = "cloudstok-assignment"
version = "0.1.0"
description = "Customer Support Agent with Chainlit and OpenAI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.9.2",
    "openai>=2.8.1",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
]
